### ISSUE TITLE
Is there any introduction to RISC-V64 and CSR registers?

### ISSUE THREAD

**Issue by stellarkey** [jzhu98/riscv-green-card#14]
Is this project still mataining?

If so, it would be great to have some content about RISC-V64 instructions and CSR registers.

Thanks.

**Comment by cnlohr** [comment]
I second this.  Still none the less, oh thank God this project exists. All of the other quick notes don't contain all the useful information here and this is formatted so well.  Man it would be awesome to see this grow to cover mover of the instruction set.  It's already particularly difficult to understand what exactly the 64-bit instructions and other extensions ... extend.
