### ISSUE TITLE
sltiu note incorrect?  (RV32I Base Integer Instructions)

### ISSUE THREAD

**Issue by MarkGFaust** [jzhu98/riscv-green-card#18]
Is this note correct?   I believe the immediate field is *sign* extended (not zero extended) and then is treated (along with rs1) as an unsigned value for the comparison.

See RISC-V Instruction Set Manual, Volume I: Unprivileged ISA, December 13, 2019.    Page 18:

"SLTI (set less than immediate) places the value 1 in register rd if register rs1 is less than the sign extended immediate when both are treated as signed numbers, else 0 is written to rd. SLTIU is
similar but compares the values as unsigned numbers (i.e., the immediate is first sign-extended to
XLEN bits then treated as an unsigned number)."

**Comment by jameslzhu** [comment]
Fixed in 9a263b416afb98372559df3a81724be49d6c97f3. Closing.
