### ISSUE TITLE
JALR immediate handling

### ISSUE THREAD

**Issue by GeoHutch** [jzhu98/riscv-green-card#2]
See pp 15-16 of https://content.riscv.org/wp-content/uploads/2016/06/riscv-spec-v2.1.pdf . JALR adds imm[11:0] (sign-extended) and rs1 to generate new PC.

**Comment by jameslzhu** [comment]
Cool, thanks!

Just as a self-note, it looks like this is the offending line: [tex/base.tex#L109](https://github.com/jameslzhu/riscv-card/blob/6f777f4cb4a957fb4803bb86bfbef01018fce2ca/tex/base.tex#L109)

```tex
jalr     & Jump And Link Reg       & I   & 1100111    & 0x0    &        & rd = PC+4; PC = rs1          & \\ \hline
```
