### ISSUE TITLE
Misplaced comments in Notes column

### ISSUE THREAD

**Issue by deller46** [jzhu98/riscv-green-card#21]
@esmil The Notes column, the first two "zero-extends" comments are mis-placed.  They should be beside the Logical Shift Right commands, not the Set Less Than instructions. @

**Comment by esmil** [comment]
@deller46 This sounds like something that is much better explained by opening a pull request fixing your problem.

**Comment by deller46** [comment]
On 2023-05-31 17:30, Emil Renner Berthing wrote:

> @deller46 [1] This sounds like something that is much better explained 
> by opening a pull request fixing your problem.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>

The problem is the issue is in a PDF that is would have to be 
replicated.  There is not something easy to edit and change *just* that 
issue.

If there were a Word doc that was used to produce the PDF in the 
repository, I'd do a pull-request.  But I don't know of any editor for 
PDF files.

This is also why there are 4 other comments mentioning other errors in 
that PDF file that have not been responded to.

Regards,

Steven Deller

Links:
------
[1] https://github.com/deller46
[2] 
https://github.com/jameslzhu/riscv-card/issues/21#issuecomment-1570984696
[3]

**Comment by esmil** [comment]
Ah no. The pdf is generated from the .tex files. The riscv-card.tex includes the files in the tex directory. I'm sure you can figure out how the tables work and make a pull request without learning all of (La)TeX

**Comment by jameslzhu** [comment]
Fixed in 21666a6, closing.
